apiVersion: v1
kind: Service
metadata:
  labels:
    name: server
  name: server
spec:
  type: LoadBalancer
  loadBalancerIP: 35.239.48.168
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    nodePort: 30061
  selector:
    name: server
