apiVersion: v1
kind: Service
metadata:
  labels:
    name: client
  name: client
spec:
 type: LoadBalancer
 ports:
    - port: 3000
      targetPort: 80
      protocol: TCP
 selector:
    name: client
